jenkins:
  master:
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "1500Mi"
    ingress:
      enabled: true
      annotations:
        dev.okteto.com/generate-host: "true"
