ghostEmail: change-me@okteto.com
ghostUsername: okteto
ghostPassword: okteto12345
allowEmptyPassword: false

ghostBlogTitle: User's Blog!

ghostProtocol: https

smtpHost: ""
smtpPort: ""
smtpUser: ""
smtpPassword: ""
smtpFromAddress: ""
smtpService: ""

mariadb:
  db:
    name: okteto
    user: okteto

  rootUser:
    password: okteto

  master:
    persistence:
      size: 10Gi

persistence:
  size: 10Gi

resources:
  limits:
    memory: 2Gi
    cpu: 1

updateStrategy:
  type: Recreate

service:
  type: ClusterIP
  annotations:
    dev.okteto.com/auto-ingress: "true"
